-- =====================================================================
-- COMPLETE PROHIRED SUPABASE DATABASE SCHEMA
-- Instructions:
-- 1. Open your Supabase Dashboard (https://supabase.com/dashboard/project/invmtctrlpmrdzgvvgkl)
-- 2. Click on "SQL Editor" on the left navigation bar
-- 3. Click "New query"
-- 4. Paste the entire content of this file and click "Run" (or Ctrl+Enter)
-- =====================================================================

-- 0. Optional Quickstart Todos table (used by Supabase quickstart / page.tsx)
CREATE TABLE IF NOT EXISTS public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_complete BOOLEAN NOT NULL DEFAULT false,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read on todos" ON public.todos;
CREATE POLICY "Allow public read on todos" ON public.todos FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated insert on todos" ON public.todos;
CREATE POLICY "Allow authenticated insert on todos" ON public.todos FOR INSERT WITH CHECK (true);

-- 1. Helper function for auto-updating timestamps
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- 2. Profiles table (user accounts & plans)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  phone TEXT,
  phone_number TEXT,
  avatar_url TEXT,
  plan TEXT NOT NULL DEFAULT 'free',
  resume_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_plan_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_plan_check CHECK (lower(plan) IN ('free', 'pro'));

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Profiles public select" ON public.profiles;
DROP POLICY IF EXISTS "Profiles public insert" ON public.profiles;
DROP POLICY IF EXISTS "Profiles public update" ON public.profiles;
DROP POLICY IF EXISTS "Profiles public delete" ON public.profiles;

CREATE POLICY "Profiles public select" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Profiles public insert" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Profiles public update" ON public.profiles FOR UPDATE USING (true);
CREATE POLICY "Profiles public delete" ON public.profiles FOR DELETE USING (true);

DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 3. Automatic Profile Creation Trigger on Auth Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  extracted_phone text;
BEGIN
  extracted_phone := COALESCE(
    new.phone,
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'phone_number',
    CASE WHEN new.email LIKE 'phone_%@%' THEN substring(new.email from 'phone_([0-9]+)@') ELSE NULL END
  );

  INSERT INTO public.profiles (id, full_name, email, phone, phone_number, plan, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email,'@',1)),
    new.email,
    extracted_phone,
    extracted_phone,
    'free',
    new.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    phone = COALESCE(profiles.phone, EXCLUDED.phone),
    phone_number = COALESCE(profiles.phone_number, EXCLUDED.phone_number),
    updated_at = now();
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. Resumes Table
CREATE TABLE IF NOT EXISTS public.resumes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  file_name TEXT NOT NULL,
  original_text TEXT,
  rewritten_resume TEXT,
  ats_score INTEGER,
  score_breakdown JSONB,
  weaknesses JSONB,
  missing_keywords JSONB,
  strengths JSONB,
  job_matches JSONB,
  audit_report JSONB,
  audited_at TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL DEFAULT 'processing' CHECK (status IN ('processing','complete','error')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS resumes_user_created_idx ON public.resumes(user_id, created_at DESC);

ALTER TABLE public.resumes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Resumes public select" ON public.resumes;
DROP POLICY IF EXISTS "Resumes public insert" ON public.resumes;
DROP POLICY IF EXISTS "Resumes public update" ON public.resumes;
DROP POLICY IF EXISTS "Resumes public delete" ON public.resumes;

CREATE POLICY "Resumes public select" ON public.resumes FOR SELECT USING (true);
CREATE POLICY "Resumes public insert" ON public.resumes FOR INSERT WITH CHECK (true);
CREATE POLICY "Resumes public update" ON public.resumes FOR UPDATE USING (true);
CREATE POLICY "Resumes public delete" ON public.resumes FOR DELETE USING (true);

DROP TRIGGER IF EXISTS resumes_updated_at ON public.resumes;
CREATE TRIGGER resumes_updated_at
  BEFORE UPDATE ON public.resumes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 5. Saved Jobs Table
CREATE TABLE IF NOT EXISTS public.saved_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  external_job_id TEXT NOT NULL,
  title TEXT NOT NULL,
  company TEXT,
  location TEXT,
  apply_url TEXT,
  salary_min INTEGER,
  salary_max INTEGER,
  saved_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(user_id, external_job_id)
);

ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "SavedJobs all own" ON public.saved_jobs;
CREATE POLICY "SavedJobs all own" ON public.saved_jobs FOR ALL USING (true) WITH CHECK (true);

-- 6. Interview Sessions Table
CREATE TABLE IF NOT EXISTS public.interview_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  role TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy','medium','hard')),
  questions JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.interview_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Interview all own" ON public.interview_sessions;
CREATE POLICY "Interview all own" ON public.interview_sessions FOR ALL USING (true) WITH CHECK (true);

-- 7. Payments Table
CREATE TABLE IF NOT EXISTS public.payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  razorpay_order_id TEXT NOT NULL UNIQUE,
  razorpay_payment_id TEXT,
  razorpay_signature TEXT,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  status TEXT NOT NULL DEFAULT 'created',
  plan TEXT NOT NULL DEFAULT 'pro_monthly',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payments_user_id ON public.payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON public.payments(created_at DESC);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Payments select own" ON public.payments;
CREATE POLICY "Payments select own" ON public.payments FOR SELECT USING (true);
DROP POLICY IF EXISTS "Payments insert public" ON public.payments;
CREATE POLICY "Payments insert public" ON public.payments FOR ALL USING (true) WITH CHECK (true);

DROP TRIGGER IF EXISTS payments_set_updated_at ON public.payments;
CREATE TRIGGER payments_set_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 8. App Configuration & Settings Table
CREATE TABLE IF NOT EXISTS public.app_config (
  id TEXT PRIMARY KEY,
  config JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all to read app_config" ON public.app_config;
CREATE POLICY "Allow all to read app_config" ON public.app_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all to update app_config" ON public.app_config;
CREATE POLICY "Allow all to update app_config" ON public.app_config FOR ALL USING (true) WITH CHECK (true);

-- Default feature flags
INSERT INTO public.app_config (id, config) VALUES ('featureFlags', '{
  "free": {
    "resumeRewrite": false,
    "resumeLimit": 1,
    "atsAnalysis": true,
    "jobMatchesView": false,
    "jobApplyLinks": false,
    "interviewPrep": false,
    "pdfDownload": true,
    "docxDownload": false
  },
  "pro": {
    "resumeRewrite": true,
    "resumeLimit": 999,
    "atsAnalysis": true,
    "jobMatchesView": true,
    "jobApplyLinks": true,
    "interviewPrep": true,
    "pdfDownload": true,
    "docxDownload": true
  }
}') ON CONFLICT (id) DO NOTHING;

-- Default settings
INSERT INTO public.app_config (id, config) VALUES ('settings', '{
  "appName": "ProHired",
  "supportEmail": "prohired@gmail.com",
  "appTagline": "Your AI-Powered Career Assistant",
  "maintenanceMode": false,
  "maintenanceMessage": "We''re improving ProHired. Back soon!",
  "proPrice": 199,
  "showLaunchBanner": true
}') ON CONFLICT (id) DO NOTHING;

-- 9. Announcements Table
CREATE TABLE IF NOT EXISTS public.announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  target TEXT NOT NULL, 
  type TEXT NOT NULL, 
  status TEXT NOT NULL DEFAULT 'sent', 
  scheduled_at TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_by TEXT DEFAULT 'admin'
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Announcements all" ON public.announcements;
CREATE POLICY "Announcements all" ON public.announcements FOR ALL USING (true) WITH CHECK (true);

-- 10. Promo Codes Table
CREATE TABLE IF NOT EXISTS public.promo_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT NOT NULL, 
  discount_value NUMERIC NOT NULL,
  max_uses INTEGER DEFAULT 0,
  used_count INTEGER DEFAULT 0,
  expires_at TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL DEFAULT 'active', 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.promo_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Promo codes all" ON public.promo_codes;
CREATE POLICY "Promo codes all" ON public.promo_codes FOR ALL USING (true) WITH CHECK (true);

-- 11. Feedback Table
CREATE TABLE IF NOT EXISTS public.feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  email TEXT,
  type TEXT NOT NULL, 
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open', 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Feedback all" ON public.feedback;
CREATE POLICY "Feedback all" ON public.feedback FOR ALL USING (true) WITH CHECK (true);

-- 12. Audit Log Table
CREATE TABLE IF NOT EXISTS public.audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  action TEXT NOT NULL,
  target_email TEXT,
  admin_email TEXT DEFAULT 'prohired@gmail.com',
  details TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Audit log all" ON public.audit_log;
CREATE POLICY "Audit log all" ON public.audit_log FOR ALL USING (true) WITH CHECK (true);

-- 13. Activity Log Table
CREATE TABLE IF NOT EXISTS public.activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  user_id UUID,
  user_email TEXT,
  details JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Activity log all" ON public.activity_log;
CREATE POLICY "Activity log all" ON public.activity_log FOR ALL USING (true) WITH CHECK (true);

-- 14. AI Usage Table
CREATE TABLE IF NOT EXISTS public.ai_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE DEFAULT CURRENT_DATE,
  feature TEXT NOT NULL,
  call_count INTEGER DEFAULT 1,
  avg_response_time NUMERIC,
  error_count INTEGER DEFAULT 0,
  cost NUMERIC DEFAULT 0,
  UNIQUE(date, feature)
);

ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "AI usage all" ON public.ai_usage;
CREATE POLICY "AI usage all" ON public.ai_usage FOR ALL USING (true) WITH CHECK (true);
